### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by pixeljava**
Changed README to add authors.

### CODE REVIEW

**Review by tahminaringer — APPROVED** [review]
Looks great! Let do this!

**Review by Doktor-Doom — COMMENTED** [review]
Lord Doom Approves

**Review by Doktor-Doom — APPROVED** [review]

**Review by tahminaringer — APPROVED** [review]

**Review by pixeljava — COMMENTED** [review]
Thanks, let's merge it.

**Review by Doktor-Doom — APPROVED** [review]
Lord Doom Reviews and Approves

**Review by SowmyaBillakanti — APPROVED** [review]
Looks good!

**Pull request merged**
